---
title: "Summarise"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Summarise}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`summarise()` is a wrapper for running both sample and feature summaries. If the `output='data.frame'` then a list is returned with the sample and feature summary `data.frames`. See the `Sample Summary` and `Feature Summary` vignettes for more information.

## Create Metaboprep object
```{r setup}
library(metaboprep)

# import data
data     <- read.csv(system.file("extdata", "dummy_data.csv",     package = "metaboprep"), header=T, row.names = 1) |> as.matrix()
samples  <- read.csv(system.file("extdata", "dummy_samples.csv",  package = "metaboprep"), header=T, row.names = 1)
features <- read.csv(system.file("extdata", "dummy_features.csv", package = "metaboprep"), header=T, row.names = 1)

# create object
m <- Metaboprep(data = data, samples = samples, features = features)

# print
m
```

## Run summary
```{r summ}
summ <- summarise(metaboprep      = m, 
                  source_layer    = "input", 
                  outlier_udist   = 1.0,
                  tree_cut_height = 0.5,
                  output          = "data.frame")

str(summ)
```
